### ISSUE TITLE
How to get sentence level sentiment?

### ISSUE THREAD

**Issue by madilk** [aliciawilliams/analyzingtext#2]
Hello,
In the Google Script, there is a function retrieveEntitySentiment to extract entity and sentiment. What if I only wanted to extract sentiment for each sentence within a document. How would the function name change? As per https://cloud.google.com/natural-language/docs/reference/rest, it should be analyzeSentiment but that didn't work. In R [googleLanguageR package], I'm able to run analyzeSentiment.

Thanks.

**Comment by aliciawilliams** [comment]
To use the analyzeSentiment method of the API, you would need to change the API endpoint URL (line 116 of the nlcall.gs file). to: `var apiEndpoint ='https://language.googleapis.com/v1/documents:analyzeSentiment?key=' + apiKey;`

Then, you would have to adjust the Apps Script in the `markEntitySentiment` function to account for the fact that the response received back is going to have a different json structure and information than what the Entity Sentiment method provides. I'll past in a few blog post links here that might help, the biggest difference is that they pull out the document sentiment rather than the sentence-level sentiment so there would still be some work to do on the code.

https://www.kutil.org/2018/03/analyse-emotion-in-oscar-movies-2018.html
https://rominirani.com/tutorial-analyzing-reviews-using-google-sheets-and-cloud-natural-language-api-240ec8f3090c
